# Site settings
title: T.L
email: liutim@live.cn
description: > # this means to ignore newlines until "baseurl:"
  Only for learning
# baseurl: "/blog" # the subpath of your site, e.g. /blog/
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tianliu.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  tianliu

# Build settings
markdown: kramdown
encoding: utf-8
highlighter: rouge

